name: Test

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test-unit:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v1

      # Setup Node.js via Volta
      - name: Volta
        uses: volta-cli/action@v1

      # Install project dependencies
      - name: Install Dependencies
        run: yarn
      # Install playwright dependencies
      - name: Install operating system dependencies
        run: npx playwright install-deps  
      # Generate static site
      - name: Generate static site
        run: yarn generate
      # Run Jest
      - name: Run Unit Tests
        run: yarn test  
      - name: Percy
        run: npx percy snapshot dist/
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}